### ISSUE TITLE
Cached version of page has wrong language context

### ISSUE THREAD

**Issue by schliflo** [trilbymedia/grav-plugin-flex-objects#106]
Following up on https://discord.com/channels/501836936584101899/506916956637495306/806574179578544148

Steps to reproduce:

- create a fresh grav project `composer create-project getgrav/grav`
- change to flex pages by adding `type: flex` to the pages settings in the `system.yaml`
- add a new file `pages/01.home/default.de.md` and add some content
- add the following language settings to `system.yaml`
    ```yaml
    default_locale: de
    languages:
      supported:
         - en
         - de
      default_lang: en
      content_fallback:
        de:
          - en
    ```
- load the `de` homepage by adding `/de/`
- everything looks fine on the first hit (page shows content of `pages/01.home/default.de.md`)
- reload page
- page shows content of `en` version (`pages/01.home/default.md`) despite of being in `de` context

I think this might be an issue with the caching or with flex itself - either way, this was working in previous versions (certainly before the 1.7 stable release). If you need info on the exact version where this was working I can dig a bit in our codebase to get it.
Please let me know if I can help any further or you need more information.
And thank you guys for taking care, this is really appreciated!
