### ISSUE TITLE
Blueprint Filepicker Field not working with Grav v1.7.5/Admin v1.10.3/Flex Objects v1.0.2 with theme@ in folder

### ISSUE THREAD

**Issue by cyberlussi** [trilbymedia/grav-plugin-flex-objects#109]
I had a working (Grav 1.6) blueprint using the filepicker element to select some png icons in the backend for a page from the theme folder. When deactivating flex objects plugin for the pages, then the blueprint worked as expected, but not with it activated. Maybe related to #71.
```
header.icon:
              type: filepicker
              folder: 'theme@:/assets/my-icons'
              label: Bild wählen
              preview_images: true
```
Now I updated to latest Grav versions (incl. cache clearing) and the filepicker does not work any more: only the previously set png is in the file picker (the value in the page yaml), no other image is shown (should be 5). The html of the file picker image renders like this:
```
<img class="filepicker-field-image" src="/backend/../theme@:/assets/my-icons/icon1.png">
``` 
So there seems something not working with the file field destination resolution (for output and for globbing the actual present files on the server).

Note: I changed the default Administrator path in the Admin-Config to "/backend", but that does not seem to be root cause as I reverted it for test.
