### ISSUE TITLE
"selectize" field type handling and filtering in list view

### ISSUE THREAD

**Issue by phmg701** [trilbymedia/grav-plugin-flex-objects#113]
Hello,
following the issue [here](https://github.com/getgrav/grav/issues/3257), there seems to be an unexpected behaviour in field representation.
Relevant my_object.yaml parts:
```
test_tags:
      type: selectize
      size: large
      label: Test Tags
      classes: fancy
      validate:
        type: commalist

test_category:
      type: selectize
      size: large
      label: Test Category
      classes: fancy
      validate:
        type: commalist
```

* added field(s) do not have the autocomplete function, otherwise found, for example, in `taxonomy` field type. This is very very helpful in creating a catalog or any other type of organized data.
* added field(s) results in ["Test1","Test2","Test3"] in list view, typical array/plain text representation.
* added field(s) cannot be searched while other text fields can. We could expect the field to be searchable, given its plain text representation of the array.

Thank you!
