### ISSUE TITLE
Allow some users to create sub-objects only in objects they’re the authors of

### ISSUE THREAD

**Issue by arkhi** [trilbymedia/grav-plugin-flex-objects#115]
This Issue is detailing the [discussion I initiated on Discord](https://discord.com/channels/501836936584101899/506916956637495306/819954483018203137).

With this structure as example:
```
root
  |- home
  |- students
    |- joe's page 
```
```yaml
# user/config/groups.yaml
[…]
students:
  groupname: students
  […]
  access:
    admin:
      super: 'false'
      login: 'true'
      pages:
        create: 'false'
        read: 'false'
        update: 'false'
        delete: 'false'
        list: 'true'
[…]
```
1. I log in with _joe_ who belongs to the _students_ group (I can only list pages).
1. A super admin has set up the following permissions to _joe’s page_:
    ```yaml
    permissions:
        authors:
            - joe
        groups:
            authors:
                create: true
                read: true
                update: true
    ```
1. I’m trying to create _first post_ into _joe’s page_ (like a personal journal).
1. _first post_ is temporarily created, waiting to be saved (:princess:).
1. I click the _Save_ button.
1. An error _Save Failed: You have insufficient permissions for task save_ appears and my changes have been discarded.

---

I tried the following on the [function _taskSave_ in flex-objects/classes/Admin/AdminController.php](https://github.com/trilbymedia/grav-plugin-flex-objects/blob/develop/classes/Admin/AdminController.php#L724), from:

```php
if (!$object->isAuthorized('create', 'admin', $this->user)) {
```
to:
```php
if (
    !$object->isAuthorized('create', 'admin', $this->user)
    && !$object->parent()->isAuthorized('create', 'admin', $this->user)
) {
```
which goal is to allow the creation of sub-objects if the logged-in user has the _create_ permissions on the parent as well.

I also needed to update the theme with a function that kicks in to add the user as the author by default, so that it inherits the permissions. Otherwise, Joe does not have any access to the page:

```php

    /**
     * Handle restrictions and initialization of the theme as early as possible.
     * […]
     */
    public function onThemeInitialized(Event $event)
    {
        […]

        $this->enable([
            'onAdminCreatePageFrontmatter' => [
                [ 'addPermissionsToPageOwned', 1 ],
            ],
        ]);
    }

    /**
     * [onAdminCreatePageFrontmatter]
     * Add the current user as author in the header when creating a page.
     * Also allows them to delete the page they created.
     * […]
     */
    public function addPermissionsToPageOwned( Event $event )
    {
        $page   = $event;
        $header = $page['header'];

        if (!isset($header['permissions']['authors'])) {
            $header['permissions']['authors'] = [
                $this->grav['admin']->user->get('username')
            ];
        }

        $header['permissions']['groups']['authors']['delete'] = true;

        $event['header'] = $header;
    }
```

Not sure if it’s any good way to solve this Issue and if it does not create other issues, but _it works for me™_ for now. :)
