### ISSUE TITLE
Unable to upload file to Flex Directory

### ISSUE THREAD

**Issue by thekenshow** [trilbymedia/grav-plugin-flex-objects#125]
Trying to create a Flex Directory that includes file attachments. I based this on an existing SimpleStorage directory I have working, with the following changes:

-  Class `Grav\Framework\Flex\Storage\FolderStorage` instead of `Grav\Framework\Flex\Storage\SimpleStorage` 
-  Folder `user-data://flex-objects/docfiles` instead of `user-data://flex-objects/docfiles.json`

I can edit and create directory items as expected, and they're stored in the configured location, but selecting a file attachment fails every time:

1. Drag file onto dropzone.
2. Image appears briefly.
3. Error shown below is displayed (selected Admin theme doesn't quite handle the text, so I highlighted it).
4. Closing the error message shows an empty dropzone.

![Screen Shot 2021-05-18 at 10 52 46 AM](https://user-images.githubusercontent.com/998832/118687264-ce794000-b7d2-11eb-90a5-d517d26d7aa1.png)

The file field is simply:

```
    docfiles:
      type: file
      label: 'Document files'
      multiple: true
      accept:
        - image/*
```
No custom templates created yet. The full blueprint appears below. What am I missing?

```
title: Documentation
description: Documentation Store.
type: flex-objects

# Flex Configuration
config:
  # Administration Configuration
  admin:
    # Admin menu (optional)
    menu:
      list:
        route: '/userdocs'
        title: User Docs
        icon: fa-fa-file-text-o
        # Authorization to collection admin
        authorize: ['admin.docs', 'admin.pages', 'admin.super']
        # Priority -10 .. 10 (highest goes up)
        priority: 2

    # Admin template type / folder
    template: default

    # List view
    list:
      title: name
      fields:
        published:
          field:
            type: toggle
            label: '<i class="fa fa-tv"></i>'
          width: 8
        postdate:
        doctitle:
          link: edit
        productline:
        srmversion:
        publicversion:

    # Edit View
    edit: 
      title:
        template: '{{ object.doctitle ?? ''Doc Title'' }}'

    # Preview View
    preview:
      enabled: false
      route:
        #template: '/plugins/flex-objects/directory:contacts'

    # Data Export
    export:
      enabled: true
      method: 'jsonSerialize'
      formatter:
        class: 'Grav\Framework\File\Formatter\YamlFormatter'
      filename: 'docfiles'

  # Site Configuration
  site:
    templates:
      collection:
        # Lookup for the template layout files for collections of objects
        paths:
          - 'flex/{TYPE}/collection/{LAYOUT}{EXT}'
      object:
        # Lookup for the template layout files for objects
        paths:
          - 'flex/{TYPE}/object/{LAYOUT}{EXT}'
      defaults:
        # Default template {TYPE}; overridden by filename of this blueprint if template folder exists
        type: default
        # Default template {LAYOUT}; can be overridden in render calls (usually Twig in templates)
        layout: default

  # Data Configuration
  data:
    # Object class to be used, allowing custom methods for the object
    object: 'Grav\Framework\Flex\FlexObject'
    # Collection class to be used, allowing custom methods for the collections
    collection: 'Grav\Framework\Flex\FlexCollection'
    # Index class to be used, works as a quick database-like lookup index
    index: 'Grav\Framework\Flex\FlexIndex'
    storage:
      # Storage class, use single file storage (does not support images and assets)
      class: 'Grav\Framework\Flex\Storage\FolderStorage'
      options:
        formatter:
          # File formatter class, in this case the file is stored in JSON
          class: 'Grav\Framework\File\Formatter\JsonFormatter'
        # JSON file where all the objects will be stored
        folder: user-data://flex-objects/docfiles
    search:
      # Search options
      options:
        contains: 1
      # Fields to be searched
      fields:
        - doctitle
        - productline
        - description
        - docfiles                

form:
  validation: loose

  fields:
    published:
      type: toggle
      label: Published
      highlight: 1
      default: 1
      options:
        1: PLUGIN_ADMIN.YES
        0: PLUGIN_ADMIN.NO
      validate:
        type: bool
        required: true

    doctitle:
      type: text
      label: Document title
      validate:
        required: true
    
    postdate:
      type: date
      label: 'Date posted'
      validate:
        required: false

    srmversion:
      type: text
      label: 'SRM Version'
      validate:
        required: true

    publicversion:
      type: text
      label: 'Public Version'
      validate:
        required: true

    draft:
      type: text
      label: 'Draft number'
      validate:
          required: false
  
    productline:
      type: select
      label: Product line
      options:
        trellixlighting: 'Trellix Lighting'
        trellixlocate: 'Trellix Locate'
        trellixcore: 'Trellix Core'
        fifthlight: 'Fifth Light'
        other: 'Other'
    
    description:
      type: textarea
      label: "Full Description"
      validate:
        type: textarea

    docfiles:
      type: file
      label: 'Document files'
      multiple: true
      limit: 0
      accept:
        - image/*
```

**Comment by mahagr** [comment]
I think this should be in the documentation:
```
  data:
    object: 'Grav\Common\Flex\Types\Generic\GenericObject'
    collection: 'Grav\Common\Flex\Types\Generic\GenericCollection'
    index: 'Grav\Common\Flex\Types\Generic\GenericIndex'
```

The Framework classes are not meant to be used directly, so if you're not creating your own classes, use the above. If you want to use your own, copy the above classes to be the base of your own.
