### ISSUE TITLE
Extend the flex-objects.yaml

### ISSUE THREAD

**Issue by evidence-sharenet** [trilbymedia/grav-plugin-flex-objects#159]
Good Day,

I have got a question. I'm new to Grav.

I want to know about how I can extend the flex-objects.yaml so that I can be able to show my own custom flex directories.

Shown below is the flex-objects.yaml file

```
enabled: true

built_in_css: true
extra_admin_twig_path: 'theme://admin/templates'
admin_list:
  per_page: 15
  order:
    by: updated_timestamp
    dir: desc

directories:
  - 'blueprints://flex-objects/pages.yaml'
  - 'blueprints://flex-objects/user-accounts.yaml'
  - 'blueprints://flex-objects/user-groups.yaml'

```

So if I want to add my own flex-object called records, how would I go about doing that?  (records.yaml file sitting in themes/[custom-theme]/blueprints/flex-objects/records.yaml)
