### ISSUE TITLE
Flex Users storage problem

### ISSUE THREAD

**Issue by Sogl** [trilbymedia/grav-plugin-flex-objects#167]
I want to store users in `accounts\username` folder.

In my `config\system.yaml`:
```yaml
accounts:
  type: flex
  storage: folder
  avatar: gravatar
```

I copied `system/blueprints/flex/user-accounts.yaml` to `user/blueprints/flex/user-accounts.yaml`. Data configuration part:
```yaml

  # Data Configuration
  data:
    object: 'Grav\Common\Flex\Types\Users\UserObject'
    collection: 'Grav\Common\Flex\Types\Users\UserCollection'
    index: 'Grav\Common\Flex\Types\Users\UserIndex'
    storage:
      class: 'Grav\Common\Flex\Types\Users\Storage\UserFolderStorage'
      options:
        formatter:
          class: 'Grav\Framework\File\Formatter\YamlFormatter'
        folder: 'account://'
        pattern: '{FOLDER}/{KEY}{EXT}'
        indexed: true
        key: username
        case_sensitive: false 
```

All should be fine but users are saved to hashed folders:

![image](https://user-images.githubusercontent.com/7556290/190709793-0b046398-97a5-4653-b8a3-f04051d88116.png)

As you can see with Xdebug, `pattern` and `storage_key` are wrong (not from our `storage` configuration):

![image](https://user-images.githubusercontent.com/7556290/190710114-65184d4a-b904-429e-ba8a-a953ece7c2f7.png)

Ok. I can extend `UserObject` to my custom to override `save()` func:
```php
<?php

declare(strict_types=1);

namespace Grav\Plugin\SoglFlex\Flex\Types\Users;

use Grav\Common\Grav;
use Grav\Common\Flex\Types\Users\UserObject as DefaultUserObject;

class UserObject extends DefaultUserObject
{
    /**
     * {@inheritdoc}
     * @see FlexObjectInterface::save()
     */
    public function save()
    {
        if (!$this->exists()) {
            $this->setStorageKey($this->getProperty('username'));
        }
        parent::save();
    }
}
```

Much better but still triple nesting:
![image](https://user-images.githubusercontent.com/7556290/190710773-c245e71c-89f3-4a16-8fac-23726fde46c1.png)

BUT when I try to override `class: 'Grav\Plugin\SoglFlex\Flex\Types\Users\UserFolderStorage'` it just not fire.

It looks as if the entire `storage` section is not being read, but the default values are being used.

@mahagr How to fix?

**Comment by Sogl** [comment]
After hours of debugging I found that if I write in `config\system.yaml`:
```yaml
accounts:
  type: flex
  storage: SOMETHING
  avatar: gravatar
```

My custom class works fine and also all other `storage` options from `user-accounts.yaml`.

However, each time of Configuration saving (in Admin panel) `storage: SOMETHING` will be overwritten. Need to add +1 value for custom or something else:
![image](https://user-images.githubusercontent.com/7556290/190875595-d22e9d85-c2fa-49e6-92c1-a6b1115aa229.png)
