### ISSUE TITLE
Date format in list view

### ISSUE THREAD

**Issue by funktionaer** [trilbymedia/grav-plugin-flex-objects#183]
I store events in a flex object. My *.yaml contains:

```
list:
      title: name
      fields:
        published:
          field:
            type: toggle
            label: Aktiv
          width: 8
        title:
          link: edit
        date:
          link: edit
```
Can I format the date in the list, because at the moment it is m/d/Y. Would be perfect if I could switch to d.m.Y

Cheers,
funktionaer
