### ISSUE TITLE
Configuration button in admin links to base URL rather than specified admin.router.configure.path

### ISSUE THREAD

**Issue by Currey** [trilbymedia/grav-plugin-flex-objects#185]
Using Grav v1.7.45, Admin v1.10.45 and Flex Objects v1.3.6.

I am trying to enable Configuration for my flex object. Within my blueprint I have set a value for `config.admin.router.actions.configure.path`. The 'Configuration' button appears in the flex directory page in admin, however, the button leads to the base URL, not the expected path. I have followed the example

To replicate, I installed a fresh instance of Grav and Flex Objects plugin. I created a flex object in `user/blueprints/flex-objects/test.yaml` and set the configure path as instructed in the [documents](https://learn.getgrav.org/17/advanced/flex/custom-types/blueprint#config-admin).

```yaml
config:
  admin:
    router:
      path: '/test'
      actions:
        configure:
          path: '/test/configure'
```

I can manually access the configuration page with `http://localhost/admin/test/configure`, but not with the 'Configuration' button in admin.

Am I missing something?
