### ISSUE TITLE
Objects not displaying properly

### ISSUE THREAD

**Issue by alpinethegreat** [trilbymedia/grav-plugin-flex-objects#28]
![cBDZvZA](https://user-images.githubusercontent.com/45307227/66252837-4d208700-e72e-11e9-96a1-41fd9f3213ea.png)

The objects aren't displaying properly on the page.

[ottawa.txt](https://github.com/trilbymedia/grav-plugin-flex-objects/files/3693045/ottawa.txt)

This is my edited contacts.json in txt form (bc github). I can't figure out why it's not working since I have another directory with the same fields that displays it just fine.

**Comment by alpinethegreat** [comment]
So I've spent all day troubleshooting by systematically changing the defaults to my edited versions to see if something broke. Nope. I changed contacts.yaml and both default.html.twig. 

Everything seems to work if I change all the default settings and point `folder:` to `user-data://flex-objects/ottawa.json`.

It just seems to break whenever I try to create a second directory.

**Comment by mahagr** [comment]
By default, this is the output for unknown types. It just dumps all the variables to the page.

You need to add some template files to render your custom type. I think we do need to add a setting which allows you to use some existing types template files instead.

**Comment by alpinethegreat** [comment]
Do you mean the frontend Twig file? I already modified the default one so would I just need to duplicate it?

**Comment by mahagr** [comment]
Yes, you need to duplicate template folder for the type and put it into a folder named identically to the new type.

**Comment by alpinethegreat** [comment]
Just to clarify, my second directory is not a different type. The type is still `flex-objects` in contacts.yaml. It's just when I duplicate contacts.yaml, and rename it just dumps all the raw code on the page.

**Comment by mahagr** [comment]
Added the following options to flex blueprints:

```
config:
  site:
    templates:
      collection:
        paths:
          - 'flex/{TYPE}/collection/{LAYOUT}{.EXT}'
      object:
        paths:
          - 'flex/{TYPE}/object/{LAYOUT}{.EXT}'
      defaults:
        type: accounts
        layout: default
```
