### ISSUE TITLE
File upload broken

### ISSUE THREAD

**Issue by schliflo** [trilbymedia/grav-plugin-flex-objects#34]
File upload fails with `Undefined index: name`:
<img width="770" alt="Screenshot 2019-10-14 at 22 55 52" src="https://user-images.githubusercontent.com/9881672/66782372-daee3600-eed5-11e9-85c9-089c01c379b3.png">

`user/blueprints/flex-objects/slides.yaml`:
```yaml
title: Slides
description: Slides for slideshows
type: flex-objects

config:
  admin:
    list:
      fields:
        header.title:
          link: edit
  data:
    object: 'Grav\Plugin\FlexObjects\Types\FlexPages\FlexPageObject'
    collection: 'Grav\Plugin\FlexObjects\Types\FlexPages\FlexPageCollection'
    index: 'Grav\Plugin\FlexObjects\Types\FlexPages\FlexPageIndex'
    storage:
      class: 'Grav\Framework\Flex\Storage\FolderStorage'
      options:
        formatter:
          class: 'Grav\Framework\File\Formatter\MarkdownFormatter'
        folder: 'user-data://slides'
        pattern: '{FOLDER}/{KEY}/default.md'
form:
  validation: loose

  fields:
    header.img:
      label: Slide Image
      help: The image used for in the slide
      type: file
      size: full
      style: vertical
      multiple: false
      destination: 'user://pages/images/'
      accept:
        - 'image/*'

    header.title:
      type: text
      autofocus: true
      style: vertical
      label: PLUGIN_ADMIN.TITLE

    content:
        type: markdown
        validate:
          type: textarea
```

**Comment by mahagr** [comment]
I've reproduced the issue.

**Comment by mahagr** [comment]
The issue is not fully fixed but goes over the error.

In the mean time, please use this blueprint:

```
title: Slides
description: Slides for slideshows
type: flex-objects

# Flex configuration
config:

  # Administration Configuration 
  admin:
    # Admin menu
    menu:
      list:
        route: '/slides'
        title: Slides
        icon: fa-address-card-o
        # Authorization to be able to see the menu item
        authorize: ['admin.pages', 'admin.super']
        # Priority -10 .. 10 (highest goes up)
        priority: 2

    # Admin template type (folder)
    template: default

    # List view
    list:
      # Fields shown in the list view
      fields:
        header.title:
          link: edit
          search: true
      # Extra options
      options:
        # Default number of records for pagination
        per_page: 20
        # Default ordering
        order:
          by: title
          dir: asc

  # Site Configuration
  site:
    templates:
      collection:
        # Lookup for the template layout files for collections of objects
        paths:
          - 'flex/{TYPE}/collection/{LAYOUT}{EXT}'
      object:
        # Lookup for the template layout files for objects
        paths:
          - 'flex/{TYPE}/object/{LAYOUT}{EXT}'
      defaults:
        # Default template {TYPE}; overridden by filename of this blueprint if template folder exists
        type: slides
        # Default template {LAYOUT}; can be overridden in render calls (usually Twig in templates)
        layout: default

  # Data Configuration
  data:
    # Object class to be used, allowing custom methods for the object
    object: 'Grav\Framework\Flex\FlexObject'
    # Collection class to be used, allowing custom methods for the collections
    collection: 'Grav\Framework\Flex\FlexCollection'
    # Index class to be used, works as a quick database-like lookup index
    index: 'Grav\Framework\Flex\FlexIndex'
    storage:
      # Storage class, if you want to have associated assets, such like images, use FolderStorage
      class: 'Grav\Framework\Flex\Storage\FolderStorage'
      options:
        formatter:
          # File formatter class, in this case the file is stored in markdown
          class: 'Grav\Framework\File\Formatter\MarkdownFormatter'
        # Folder where all the objects will be stored
        folder: 'user-data://slides'
        # File pattern to generate the filename
        pattern: '{FOLDER}/{KEY}/slide{EXT}'
        # Field which will be used as {KEY}
        key: storage_key
        # Keep index file in filesystem to speed up lookups
        indexed: true
    search:
      # Search options
      options:
        contains: 1
      # Fields to be searched
      fields:
        - header.title

# Regular form definition
form:
  validation: loose

  fields:
    header.img:
      label: Slide Image
      help: The image used for in the slide
      type: file
      size: full
      style: vertical
      multiple: false
      accept:
        - 'image/*'

    header.title:
      type: text
      autofocus: true
      style: vertical
      label: PLUGIN_ADMIN.TITLE

    markdown:
      type: markdown
      validate:
        type: textarea
```
