### ISSUE TITLE
Flex Object with file field not working

### ISSUE THREAD

**Issue by chesjon** [trilbymedia/grav-plugin-flex-objects#37]
I am having trouble getting a field of type file working within a flex object blueprint. In the administration panel I am presented with the option to select a file but when I save the file is not there as if it did not upload. The value for the file field in the markdown is also empty:

```
---
name: 'Fraser Fir'
price: '60'
description: 'Test Description'
img: {  }
---
```

Here is my flex object blueprint

```
title: Trees
type: flex-objects

# Flex Configuration
config:
  # Administration Configuration
  admin:
    # Admin menu (optional)
    menu:
      list:
        route: '/trees'
        title: Trees
        icon: fa-address-card-o
        # Authorization to collection admin
        authorize: ['admin.pages', 'admin.super']
        # Priority -10 .. 10 (highest goes up)
        priority: 2

    # Admin template type / folder
    template: default

    # List view
    list:
      title: name
      fields:
        header.name:
          link: edit
        header.price:
          link: edit
        header.description:
          link: edit

    # Edit View
    edit:
      title:
        template: '{{ object.name ?? ''Tree'' }}'

    # Data Export
    export:
      enabled: true
      method: 'jsonSerialize'
      formatter:
        class: 'Grav\Framework\File\Formatter\YamlFormatter'
      filename: 'trees'

  # Site Configuration
  site:
    templates:
      collection:
        # Lookup for the template layout files for collections of objects
        paths:
          - 'flex/{TYPE}/collection/{LAYOUT}{EXT}'
      object:
        # Lookup for the template layout files for objects
        paths:
          - 'flex/{TYPE}/object/{LAYOUT}{EXT}'
      defaults:
        # Default template {TYPE}; overridden by filename of this blueprint if template folder exists
        type: trees
        # Default template {LAYOUT}; can be overridden in render calls (usually Twig in templates)
        layout: default

  # Data Configuration
  data:
    # Object class to be used, allowing custom methods for the object
    object: 'Grav\Framework\Flex\FlexObject'
    # Collection class to be used, allowing custom methods for the collections
    collection: 'Grav\Framework\Flex\FlexCollection'
    # Index class to be used, works as a quick database-like lookup index
    index: 'Grav\Framework\Flex\FlexIndex'
    storage:
      # Storage class, if you want to have associated assets, such like images, use FolderStorage
      class: 'Grav\Framework\Flex\Storage\FolderStorage'
      options:
        formatter:
          # File formatter class, in this case the file is stored in markdown
          class: 'Grav\Framework\File\Formatter\MarkdownFormatter'
        # Folder where all the objects will be stored
        folder: user-data://flex-objects
        # File pattern to generate the filename
        pattern: '{FOLDER}/{KEY}/tree{EXT}'
        # Field which will be used as {KEY}
        key: storage_key
        # Keep index file in filesystem to speed up lookups
        indexed: true
    search:
      # Search options
      options:
        contains: 1
      # Fields to be searched
      fields:
        - header.name
        - header.price
        - header.description

form:
  validation: loose

  fields:

    header.name:
      type: text
      label: Name
      validate:
        required: true

    header.price:
      type: text
      label: Price
      validate:
        required: true

    header.description:
      type: textarea
      label: Description
      validate:
        required: true

    header.img:
      label: Tree Image
      type: file
      multiple: false
      accept:
        - 'image/*'
```

Grav version: 1.7.0-rc.1
Admin: 1.10.0-rc.1
Form Plugin: 4.0.0

I have tried with and without the destination defined for the header.img field.

I am hoping someone can help me identify whether this is a bug with the flex objects or if I am doing something wrong.

Thank you!
