### ISSUE TITLE
Directory Export with CsvFormatter.php Throws Array to String Conversion Error

### ISSUE THREAD

**Issue by thekenshow** [trilbymedia/grav-plugin-flex-objects#54]
I tried to configure the directory export to generate CSV but it throws an `Array to string conversion` error of on line 117 of `system/src/Grav/Framework/File/Formatter/CsvFormatter.php`. 

```
    protected function encodeLine(array $line, $delimiter = null): string
    {
        foreach ($line as $key => &$value) {
            $value = $this->escape((string)$value); // LINE 117
        }
        unset($value);
 
        return implode($delimiter, $line). "\n";
    }
```

Here's my configuration:

```
config:
  admin:
    export:
      title: CSV
      enabled: true
      formatter:
        class: 'Grav\Framework\File\Formatter\CsvFormatter'
```

Maybe because I have a selectize field in my data? 

```
    tags:
      type: selectize
      selectize:
        create: false
        options:
            - text: "Water"
              value: "Water"
            - text: "Indigenous"
              value: "Indigenous"
            - text: "Advocacy"
              value: "Advocacy"
```
