### ISSUE TITLE
SimpleStorage and File Upload?

### ISSUE THREAD

**Issue by clivebeckett** [trilbymedia/grav-plugin-flex-objects#61]
As far as I understand it, it is not supposed to be possible to add a file upload field to a data object stored with `Grav\Framework\Flex\Storage\SimpleStorage`. Is this correct?

I believe this should be possible – just as it was in the **Flex Directory** plugin _(see below)._ Even if file uploads will eventually be possible with `Grav\Framework\Flex\Storage\FolderStorage` (see issue #34), there is one big downside to it. Using the blueprint settings as posted in issue #34 there will be a folder and file for each record. With a large dataset this just isn’t human readable anymore and you will not be able to properly edit the datasets outside of the Admin Plugin, especially with the folder named after the storage_key. Additionally I assume that having Grav read a huge set of small files for one list of data is less efficient than reading one large file.

### My usecase

I want to set up a Flex Object _discography_ for a musician’s website in order to create different pages with (overlapping) subsets of the discography data. I would like to have the following data structure:

`user/data/discography/discography.yaml` containing the data of all records
`user/data/discography/images` containing all the album covers

### Possible workaround

If there was a way with `Grav\Framework\Flex\Storage\FolderStorage` to name the folder for each record as a URL version _(lowercase, no spaces or special characters)_ of different fields instead of the storage_key, that would make it human readable and thus editable through the file browser:
`user/data/discography/{year}-{artist}-{album_title}/album.yaml`

### Flex Directory

In the old [Flex Directory plugin](https://github.com/trilbymedia/grav-plugin-flex-directory) a simple file upload was possible using the following field settings:

```
  fields:
    cover_image:
      type: file
      label: Cover Image
      destination: user-data://discography/images
      multiple: false
      accept:
        - image/*
```

**Comment by rhukster** [comment]
Can you please test with this branch: https://github.com/getgrav/grav/tree/feature/1.7-media

**Comment by clivebeckett** [comment]
@rhukster Thanks a lot! I tested it with this branch and it works partly. Upload works fine – deleting a file however only removes the file listing from the dataset but does not remove the file from the folder. Also when deleting a dataset completely, the file will stay in the folder.

### Setup

**discography.yaml** (excerpts)
```yaml
  data:
    storage:
      class: 'Grav\Framework\Flex\Storage\SimpleStorage'
#[...]
  fields:
    #[...]
    cover_image:
      type: file
      label: Cover Image
      #destination: user-data://discography/images
      destination: 'user/data/discography/images'
      multiple: false
      accept:
        - image/*
```

There is an additional small issue with `destination: user-data://discography/images`: the thumbnail image did not show as it was referenced with a double slash: `<img src="//user/data/discography/images/..."`

Cheers,
Clive.
