### ISSUE TITLE
[Users] Save Failed: Failed to move uploaded file

### ISSUE THREAD

**Issue by ricardo118** [trilbymedia/grav-plugin-flex-objects#70]
How to replicate:

Switch User Accounts storage to Folder

Attempt to upload an avatar.

Saves correctly inside user.yaml but no file/folder created.

data stored in user.yaml:

```
avatar:
  user/accounts/avatars/V1m54WNoKp0hdiY.jpg:
    name: V1m54WNoKp0hdiY.jpg
    type: image/jpeg
    size: 151548
    path: user/accounts/avatars/V1m54WNoKp0hdiY.jpg
```

Shouldnt the avatar be stored inside the user itself if using folder storage?

**Comment by ricardo118** [comment]
Continued:

for reference also tested with a custom upload field:

```
    images:
      type: file
      style: vertical
      label: Images
      destination: '@self'
      multiple: true
```

Result:
` Save Failed: Failed to move uploaded file`

Saved to file:
```
images:
  MS1_3206.jpg:
    name: MS1_3206.jpg
    type: image/jpeg
    size: 151548
    path: MS1_3206.jpg
```
