### ISSUE TITLE
Page Blueprint with filepicker field does not recognize folder value of @self 

### ISSUE THREAD

**Issue by thekenshow** [trilbymedia/grav-plugin-flex-objects#71]
The blueprint below was applied to a 1.7-rc15 module page in a site configured with Frontend Page Type: Flex Objects. 

When the `.itemimage` field is set to `@self` (or `@page.self`, or `self@`), it gets rendered as an empty box instead of displaying a list of images attached to that page.

When `.itemimage` is set to blank in the blueprint, e.g., '', it works as expected.

```
title: 'Info List'
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          
          fields:
            header.slogan:
              type: text
              label: Slogan
              help: "Use for home slide when featuring this section"
            header.listitems:
              type: list
              style: vertical
              label: 'List items'
              collapsed: true
              fields:
                .itemimage:
                  type: filepicker
                  folder: '@self'
                  label: 'Choose an image from this page media'
                  preview_images: true
```
