### ISSUE TITLE
update_user: true Process sometimes failing to save/saved double

### ISSUE THREAD

**Issue by ricardo118** [trilbymedia/grav-plugin-flex-objects#77]
Using a frontend user profile with `update_user: true` and image/video uploads will cause wrong saved paths and sometimes doubled

```
video:
  user/pages/area-pessoal/video.mp4:
    name: video.mp4
    type: video/mp4
    size: 59571279
    path: user/pages/area-pessoal/video.mp4
  video.mp4:
    name: video.mp4
    type: video/mp4
    size: 59571279
    path: video.mp4
foto:
  user/pages/area-pessoal/kasutera.png:
    name: kasutera.png
    type: image/png
    size: 1497165
    path: user/pages/area-pessoal/kasutera.png
  kasutera.png:
    name: kasutera.png
    type: image/png
    size: 1497165
    path: kasutera.png
```
