### ISSUE TITLE
Taxonomy field deserialize not working

### ISSUE THREAD

**Issue by stephan-strate** [trilbymedia/grav-plugin-flex-objects#90]
I added the taxonomy field type to contacts flex object by overriding it.
```yaml
    taxonomy:
      type: taxonomy
      label: PLUGIN_ADMIN.TAXONOMY
      multiple: true
      validate:
        type: array
      taxonomies:
        - 'category'
```

The field appears as expected, and saves the selected values to the json file. But it does not deserialize the value and shows it in the taxonomy field again.

```json
    {"taxonomy":{"category":["Important"]}}
```
